apiVersion: v1 
kind: Pod
metadata: 
  name: conversao-temperatura
spec: 
  containers:
    - name: web
      image: kubedevio/web-page:blue
      ports:
        - containerPort: 80

---

apiVersion: v1 
kind: Pod
metadata: 
  name: conversao-label
  labels:
    app: web
spec: 
  containers:
    - name: web
      image: glasscode/conversao-temperatura:v1
      ports:
        - containerPort: 80